package enums;

/**
 * Informations accessibles par la config
 * @author pf
 *
 */

public enum ConfigInfo {
	TABLE_X,
	TABLE_Y,
	DUREE_MATCH_EN_S,
	TEMPS_FUNNY_ACTION,
	LARGEUR_ROBOT,
	LONGUEUR_ROBOT,
	RAYON_ROBOT,
	RAYON_ROBOT_ADVERSE,
	SLEEP_BOUCLE_ACQUITTEMENT,
	COULEUR,
	HORIZON_CAPTEURS,
	DUREE_PEREMPTION_OBSTACLES,
	CAPTEURS_FREQUENCE,
	CAPTEURS_TEMPORISATION_OBSTACLES,
	DISTANCE_DETECTION,
	CAPTEURS_ON,
	AFFICHE_DEBUG,
	SAUVEGARDE_FICHIER,
	LASERS_FREQUENCE,
	DISTANCE_MAX_ENTRE_MESURE_ET_OBJET,
	HOOKS_TOLERANCE_MM,
	DISQUE_TOLERANCE_MAJ,
	DISQUE_TOLERANCE_CONSIGNE,
	TRAJECTOIRE_COURBE,
	NB_TENTATIVES,
	ANTICIPATION_TRAJECTOIRE_COURBE,
	ANGLE_DEGAGEMENT_ROBOT,
	DISTANCE_DEGAGEMENT_ROBOT,
	MARGE,
	TEMPS_MAX_ANTICIPATION,
	DATE_PRECISION_DIMINUE,
	EVITE_ELEMENT_JEU,
	TEST1;
	
}
